// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 a = 1;</code>
   * @return The a.
   */
  long getA();

  /**
   * <code>int64 b = 2;</code>
   * @return The b.
   */
  long getB();
}
