// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public final class Calculator {
  private Calculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrimeNumberDecompositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrimeNumberDecompositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrimeNumberDecompositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrimeNumberDecompositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeAverageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeAverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeAverageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeAverageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindMaximumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindMaximumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindMaximumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindMaximumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"\"\n\nAddRequest\022\t\n\001a\030\001 " +
      "\001(\003\022\t\n\001b\030\002 \001(\003\"\035\n\013AddResponse\022\016\n\006result\030" +
      "\001 \001(\003\"\027\n\nSumRequest\022\t\n\001x\030\001 \003(\003\"\035\n\013SumRes" +
      "ponse\022\016\n\006result\030\001 \001(\003\"1\n\037PrimeNumberDeco" +
      "mpositionRequest\022\016\n\006number\030\001 \001(\003\"2\n Prim" +
      "eNumberDecompositionResponse\022\016\n\006number\030\001" +
      " \001(\003\"\'\n\025ComputeAverageRequest\022\016\n\006number\030" +
      "\001 \001(\005\")\n\026ComputeAverageResponse\022\017\n\007avera" +
      "ge\030\001 \001(\001\"$\n\022FindMaximumRequest\022\016\n\006number" +
      "\030\001 \001(\005\"&\n\023FindMaximumResponse\022\017\n\007maximum" +
      "\030\001 \001(\0052\275\002\n\021CalculatorService\022 \n\003Add\022\013.Ad" +
      "dRequest\032\014.AddResponse\022 \n\003Sum\022\013.SumReque" +
      "st\032\014.SumResponse\022a\n\030PrimeNumberDecomposi" +
      "tion\022 .PrimeNumberDecompositionRequest\032!" +
      ".PrimeNumberDecompositionResponse0\001\022C\n\016C" +
      "omputeAverage\022\026.ComputeAverageRequest\032\027." +
      "ComputeAverageResponse(\001\022<\n\013FindMaximum\022" +
      "\023.FindMaximumRequest\032\024.FindMaximumRespon" +
      "se(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddRequest_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumRequest_descriptor,
        new java.lang.String[] { "X", });
    internal_static_SumResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_PrimeNumberDecompositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PrimeNumberDecompositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrimeNumberDecompositionRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_PrimeNumberDecompositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PrimeNumberDecompositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrimeNumberDecompositionResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_ComputeAverageRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ComputeAverageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeAverageRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_ComputeAverageResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ComputeAverageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeAverageResponse_descriptor,
        new java.lang.String[] { "Average", });
    internal_static_FindMaximumRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_FindMaximumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindMaximumRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_FindMaximumResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_FindMaximumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindMaximumResponse_descriptor,
        new java.lang.String[] { "Maximum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
