// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface ComputeAverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ComputeAverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double average = 1;</code>
   * @return The average.
   */
  double getAverage();
}
