// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface FindMaximumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindMaximumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
