// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface FindMaximumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindMaximumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 maximum = 1;</code>
   * @return The maximum.
   */
  int getMaximum();
}
