// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface PrimeNumberDecompositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberDecompositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   * @return The number.
   */
  long getNumber();
}
