// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 result = 1;</code>
   * @return The result.
   */
  long getResult();
}
