// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 x = 1;</code>
   * @return A list containing the x.
   */
  java.util.List<java.lang.Long> getXList();
  /**
   * <code>repeated int64 x = 1;</code>
   * @return The count of x.
   */
  int getXCount();
  /**
   * <code>repeated int64 x = 1;</code>
   * @param index The index of the element to return.
   * @return The x at the given index.
   */
  long getX(int index);
}
