//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializeaddResponse")
public inline fun addResponse(block: AddResponseKt.Dsl.() -> kotlin.Unit): AddResponse =
  AddResponseKt.Dsl._create(AddResponse.newBuilder()).apply { block() }._build()
public object AddResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: AddResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: AddResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): AddResponse = _builder.build()

    /**
     * <code>int64 result = 1;</code>
     */
    public var result: kotlin.Long
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>int64 result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun AddResponse.copy(block: AddResponseKt.Dsl.() -> kotlin.Unit): AddResponse =
  AddResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

