//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializeaddRequest")
public inline fun addRequest(block: AddRequestKt.Dsl.() -> kotlin.Unit): AddRequest =
  AddRequestKt.Dsl._create(AddRequest.newBuilder()).apply { block() }._build()
public object AddRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: AddRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: AddRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): AddRequest = _builder.build()

    /**
     * <code>int64 a = 1;</code>
     */
    public var a: kotlin.Long
      @JvmName("getA")
      get() = _builder.getA()
      @JvmName("setA")
      set(value) {
        _builder.setA(value)
      }
    /**
     * <code>int64 a = 1;</code>
     */
    public fun clearA() {
      _builder.clearA()
    }

    /**
     * <code>int64 b = 2;</code>
     */
    public var b: kotlin.Long
      @JvmName("getB")
      get() = _builder.getB()
      @JvmName("setB")
      set(value) {
        _builder.setB(value)
      }
    /**
     * <code>int64 b = 2;</code>
     */
    public fun clearB() {
      _builder.clearB()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun AddRequest.copy(block: AddRequestKt.Dsl.() -> kotlin.Unit): AddRequest =
  AddRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

