//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializefindMaximumRequest")
public inline fun findMaximumRequest(block: FindMaximumRequestKt.Dsl.() -> kotlin.Unit): FindMaximumRequest =
  FindMaximumRequestKt.Dsl._create(FindMaximumRequest.newBuilder()).apply { block() }._build()
public object FindMaximumRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: FindMaximumRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: FindMaximumRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): FindMaximumRequest = _builder.build()

    /**
     * <code>int32 number = 1;</code>
     */
    public var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>int32 number = 1;</code>
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun FindMaximumRequest.copy(block: FindMaximumRequestKt.Dsl.() -> kotlin.Unit): FindMaximumRequest =
  FindMaximumRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

