//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializeprimeNumberDecompositionRequest")
public inline fun primeNumberDecompositionRequest(block: PrimeNumberDecompositionRequestKt.Dsl.() -> kotlin.Unit): PrimeNumberDecompositionRequest =
  PrimeNumberDecompositionRequestKt.Dsl._create(PrimeNumberDecompositionRequest.newBuilder()).apply { block() }._build()
public object PrimeNumberDecompositionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: PrimeNumberDecompositionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: PrimeNumberDecompositionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): PrimeNumberDecompositionRequest = _builder.build()

    /**
     * <code>int64 number = 1;</code>
     */
    public var number: kotlin.Long
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>int64 number = 1;</code>
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun PrimeNumberDecompositionRequest.copy(block: PrimeNumberDecompositionRequestKt.Dsl.() -> kotlin.Unit): PrimeNumberDecompositionRequest =
  PrimeNumberDecompositionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

