//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializeprimeNumberDecompositionResponse")
public inline fun primeNumberDecompositionResponse(block: PrimeNumberDecompositionResponseKt.Dsl.() -> kotlin.Unit): PrimeNumberDecompositionResponse =
  PrimeNumberDecompositionResponseKt.Dsl._create(PrimeNumberDecompositionResponse.newBuilder()).apply { block() }._build()
public object PrimeNumberDecompositionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: PrimeNumberDecompositionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: PrimeNumberDecompositionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): PrimeNumberDecompositionResponse = _builder.build()

    /**
     * <code>int64 number = 1;</code>
     */
    public var number: kotlin.Long
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>int64 number = 1;</code>
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun PrimeNumberDecompositionResponse.copy(block: PrimeNumberDecompositionResponseKt.Dsl.() -> kotlin.Unit): PrimeNumberDecompositionResponse =
  PrimeNumberDecompositionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

