//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calculator.proto

@kotlin.jvm.JvmName("-initializesumRequest")
public inline fun sumRequest(block: SumRequestKt.Dsl.() -> kotlin.Unit): SumRequest =
  SumRequestKt.Dsl._create(SumRequest.newBuilder()).apply { block() }._build()
public object SumRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: SumRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: SumRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): SumRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class XProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated int64 x = 1;</code>
     */
     public val x: com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getXList()
      )
    /**
     * <code>repeated int64 x = 1;</code>
     * @param value The x to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addX")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.add(value: kotlin.Long) {
      _builder.addX(value)
    }/**
     * <code>repeated int64 x = 1;</code>
     * @param value The x to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignX")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.plusAssign(value: kotlin.Long) {
      add(value)
    }/**
     * <code>repeated int64 x = 1;</code>
     * @param values The x to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllX")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Long>) {
      _builder.addAllX(values)
    }/**
     * <code>repeated int64 x = 1;</code>
     * @param values The x to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllX")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Long>) {
      addAll(values)
    }/**
     * <code>repeated int64 x = 1;</code>
     * @param index The index to set the value at.
     * @param value The x to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setX")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.set(index: kotlin.Int, value: kotlin.Long) {
      _builder.setX(index, value)
    }/**
     * <code>repeated int64 x = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearX")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Long, XProxy>.clear() {
      _builder.clearX()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun SumRequest.copy(block: SumRequestKt.Dsl.() -> kotlin.Unit): SumRequest =
  SumRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

